##
## Travis
## https://travis-ci.com/
##
## https://travis-ci.com/rotators/foclassic/
##

os: linux
sudo: required
notifications:
 email: false

language: cpp
env:
 - GXX=5
 - GXX=6
 - GXX=7
 - GXX=8

matrix:
 allow_failures:
  - env: GXX=6
  - env: GXX=7
  - env: GXX=8

git:
 depth: false

cache:
 apt: true
 directories:
  - SDK.Cache

before_install:
 - export CC=gcc-${GXX} CXX=g++-${GXX}
 - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
 - sudo apt-get update
 - sudo apt-get install -y ${CC}-multilib ${CXX}-multilib
 - sudo apt-get install -y libx11-dev:i386 libxft-dev:i386 libxi-dev:i386 libxinerama-dev:i386 libgl1-mesa-dev:i386 libglu1-mesa-dev:i386 freeglut3-dev:i386 libfreetype6-dev:i386 libfontconfig-dev:i386 libpng-dev:i386

install:
 - export PATH=SDK.Cache/cmake/bin:$PATH
 - cmake -DO=Build.cmake -DOWNLOAD_DIR=SDK.Cache -P CMake/SelfUpdate/SelfUpdate.cmake && hash -r

script:
 - cmake -P Build.cmake
